apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: stp-console-menu
spec:
  applicationMenu:
    imageURL: 'https://i.ibb.co/pZ0Lxdb/Logo-Red-Hat-Hat-Color-RGB.png'
    section: Red Hat STP
  href: 'https://github.com/mmwillingham/acm'
  location: ApplicationMenu
  text: STP GitHub Repository