apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: main-policy
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/subscriptions: acm-policies/main-policy-subscription-1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"app.k8s.io/v1beta1","kind":"Application","metadata":{"annotations":{},"name":"main-policy","namespace":"acm-policies"},"spec":{"componentKinds":[{"group":"apps.open-cluster-management.io","kind":"Subscription"}],"descriptor":{},"selector":{"matchExpressions":[{"key":"app","operator":"In","values":["main-policy"]}]}}}
    open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
    open-cluster-management.io/user-identity: a3ViZWFkbWlu
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - main-policy
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-mmwillingham-acm-acs-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ggithubcom-mmwillingham-acm-acs
  namespace: ggithubcom-mmwillingham-acm-acs-ns
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  selfLink:
spec:
  type: Git
  pathname: https://github.com/mmwillingham/acm-acs.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: main-policy-subscription-1
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: acm-policies
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: main-policy
    app.kubernetes.io/part-of: main-policy
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: ggithubcom-mmwillingham-acm-acs-ns/ggithubcom-mmwillingham-acm-acs
  placement:
    placementRef:
      name: main-policy-placement
      kind: Placement
      #kind: PlacementRule
posthooks: {}
prehooks: {}
---
#  PlacementRule example instead of Placement
#apiVersion: cluster.open-cluster-management.io/v1beta1
#kind: Placement
#metadata:
#  name: main-policy-placement
#  namespace: acm-policies
#  labels:
#    app: main-policy
#  selfLink:
#spec:
#  predicates:
#   - requiredClusterSelector:
#        labelSelector:
#          matchExpressions:
#            - key: vendor
#              operator: In
#              values:
#              - OpenShift
##  clusterSets:
##    - hub
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: hub
  namespace: acm-policies
spec:
  clusterSet: hub
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: main-policy-placement
  namespace: acm-policies
spec:
  clusterSets:
    - hub
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - {key: name, operator: In, values: ["local-cluster"]}
