apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: helmrepos
  namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: day2/manifests/helmrepos
    repoURL: https://github.com/acm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #- CreateNamespace=true