#  Use this one for testing an individual cluster or more
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-named-clusters
  namespace: acm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
#          - paas-rosa-dev
#          - ccoe-dev