# I haven't tested this
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-exclude-specified-clusters
  namespace: acm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: name
        operator: NotIn
        values:
          - dl-rosa01-1d
