apiVersion: v1
kind: Namespace
metadata:
  name: openshift-terminal
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: openshift-operators
spec:
  name: web-terminal
  channel: fast
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
